Cert manager
Multiwoven/helm-charts pull request #12
Opened 2024-05-02 22:50 UTC by AngeloB-AIS

2024-05-02 22:55 UTC, RafaelOAiSquared requested changes
Delete the `.DS_Store` files.

2024-05-02 22:55 UTC, RafaelOAiSquared commented on charts/multiwoven/values.yaml
> +  tlsAdminEmail: admin@squared.ai
The default should be something like: `admin@example.com`

2024-05-02 22:55 UTC, RafaelOAiSquared commented on charts/multiwoven/templates/multiwoven-config.yaml
> +  VITE_BRAND_LOGO: {{ .Values.multiwovenConfig.viteBrandLogo | quote }}
Delete `VITE_BRAND_LOGO` here and delete `viteBrandLogo` from `values.yaml`

2024-05-02 23:04 UTC, AngeloB-AIS commented on charts/multiwoven/values.yaml
> +  tlsAdminEmail: admin@squared.ai
how about admin@multiwoven.com?

2024-05-03 00:00 UTC, RafaelOAiSquared approved these changes

2024-05-03 13:17 UTC, subintp approved these changes

2024-05-03 13:17 UTC, merged