feat: add env variable GRPC_ENABLE_FORK_SUPPORT
Multiwoven/helm-charts pull request #34
Opened 2024-07-08 12:29 UTC by RafaelOAiSquared

Add env variable GRPC_ENABLE_FORK_SUPPORT

2024-07-08 12:29 UTC, subintp requested changes

2024-07-08 12:29 UTC, subintp commented on charts/multiwoven/values.yaml
> +  grpcEnableForkSupport: ""
@RafaelOAiSquared  Can we keep this as 1

2024-07-08 14:12 UTC, RafaelOAiSquared commented on charts/multiwoven/values.yaml
> +  grpcEnableForkSupport: ""
@subintp yes, updated PR

2024-07-09 12:04 UTC, subintp approved these changes

2024-07-09 12:04 UTC, merged